"""Application-layer workflows for file I/O, editing, validation, and solving."""

from .errors import ApplicationError, NetworkPersistenceError, SolverSelectionError
from .interactors import (
    add_connection,
    add_node,
    build_connection_result_map,
    build_node_result_map,
    build_result_snapshot,
    clone_network,
    create_empty_network,
    delete_network_file,
    export_network_spec,
    get_network_summary,
    get_solver_metadata,
    import_network_spec,
    inspect_connection,
    inspect_node,
    list_solvers,
    load_network,
    remove_connection,
    remove_node,
    reverse_connection_orientation,
    save_network,
    save_result_snapshot,
    solve_network,
    solve_network_file,
    update_connection,
    update_node,
    validate_network,
)
from .models import (
    ConnectionDetails,
    NetworkSummary,
    NodeDetails,
    SolveOutcome,
    SolveSession,
    SolverInfo,
    ValidationSummary,
)
from .solvers import get_default_solver_name

__all__ = [
    "ApplicationError",
    "NetworkPersistenceError",
    "SolverSelectionError",
    "SolverInfo",
    "NetworkSummary",
    "ValidationSummary",
    "NodeDetails",
    "ConnectionDetails",
    "SolveOutcome",
    "SolveSession",
    "add_connection",
    "add_node",
    "build_connection_result_map",
    "build_node_result_map",
    "build_result_snapshot",
    "clone_network",
    "create_empty_network",
    "delete_network_file",
    "export_network_spec",
    "get_default_solver_name",
    "get_network_summary",
    "get_solver_metadata",
    "import_network_spec",
    "inspect_connection",
    "inspect_node",
    "list_solvers",
    "load_network",
    "remove_connection",
    "remove_node",
    "reverse_connection_orientation",
    "save_network",
    "save_result_snapshot",
    "solve_network",
    "solve_network_file",
    "update_connection",
    "update_node",
    "validate_network",
]
