"""Solver-facing hydraulic model exports."""

from .connections import (
    DW_pipe,
    FactorPolynomialConnection,
    FixedKQn_pipe,
    KQn_pipe,
    LinearInterpolationConnection,
    Pipe,
    PolynomialRegressionConnection,
    darcy_weisbach_friction_factor,
    darcy_weisbach_head_loss,
    fit_power_law_parameters_from_samples,
    laminar_power_law_parameters,
    local_power_law_head_loss_from_darcy,
    local_power_law_parameters_from_darcy,
    power_law_flow_rate,
    power_law_head_loss,
)
from .factory import (
    build_node_from_spec,
    build_system_from_spec,
    create_connection,
    create_connection_from_spec,
    export_connection_parameter_schema,
    export_connection_spec,
    export_node_spec,
    export_system_spec,
    get_connection_constructor,
    get_connection_parameter_schema,
    get_connection_parameter_template,
    get_connection_type_name,
    load_system_from_json,
    list_connection_types,
    register_connection_type,
    save_system_to_json,
)
from .nodes import Node
from .parameters import ParameterSpec, Parameterized
from .results import (
    ConnectionResult,
    NodeResult,
    SolveResult,
    build_connection_results,
    build_node_results,
)
from .solvers import list_solver_names, solve
from .systems import Connection, ConnectionEntry, HydraulicSystem

__all__ = [
    "Pipe",
    "DW_pipe",
    "KQn_pipe",
    "FixedKQn_pipe",
    "LinearInterpolationConnection",
    "PolynomialRegressionConnection",
    "FactorPolynomialConnection",
    "darcy_weisbach_friction_factor",
    "darcy_weisbach_head_loss",
    "power_law_head_loss",
    "power_law_flow_rate",
    "laminar_power_law_parameters",
    "local_power_law_parameters_from_darcy",
    "local_power_law_head_loss_from_darcy",
    "fit_power_law_parameters_from_samples",
    "list_connection_types",
    "get_connection_constructor",
    "get_connection_parameter_schema",
    "export_connection_parameter_schema",
    "get_connection_parameter_template",
    "get_connection_type_name",
    "register_connection_type",
    "create_connection",
    "create_connection_from_spec",
    "export_connection_spec",
    "Connection",
    "Node",
    "ConnectionEntry",
    "HydraulicSystem",
    "build_node_from_spec",
    "export_node_spec",
    "build_system_from_spec",
    "export_system_spec",
    "load_system_from_json",
    "save_system_to_json",
    "Parameterized",
    "ParameterSpec",
    "NodeResult",
    "ConnectionResult",
    "SolveResult",
    "build_node_results",
    "build_connection_results",
    "solve",
    "list_solver_names",
]
