"""Hydranet MVP004 public API."""

from .analysis import (
    DiagnosticItem,
    ModelSample,
    ScenarioComparison,
    build_connection_results_csv,
    build_diagnostics,
    build_model_samples_csv,
    build_model_samples_payload,
    build_node_results_csv,
    build_report_payload,
    build_report_csv,
    build_text_report,
    build_scenario_csv,
    build_trace_csv,
    clone_network,
    run_scenario_analysis,
    sample_model,
)
from .application import (
    create_network,
    load_network_file,
    save_network_file,
    solve_network_file,
    validate_network_file,
)
from .gui import run_gui
from .io import build_network_spec, load_network, network_from_spec, save_network
from .models import (
    ConnectionModel,
    DarcyPowerLawPipe,
    DarcyWeisbachPipe,
    FactorPolynomialConnection,
    LinearInterpolationConnection,
    PolynomialRegressionConnection,
    PowerLawPipe,
    darcy_weisbach_friction_factor,
    darcy_weisbach_head_variation,
    fit_power_law_parameters_from_samples,
    laminar_power_law_parameters,
    local_power_law_head_variation_from_darcy,
    local_power_law_parameters_from_darcy,
    power_law_flow_rate,
    power_law_head_variation,
)
from .launcher import main as launch_app
from .network import Connection, Network, Node, ValidationReport
from .parameters import (
    ParameterSpec,
    build_parameter_template,
    export_parameter_schema,
    validate_parameter_values,
)
from .registry import (
    build_model,
    get_model_class,
    get_model_parameter_schema,
    get_model_parameter_template,
    list_model_types,
)
from .results import ConnectionResult, NodeResult, SolveResult, SolveTraceStep
from .solver import (
    CONTINUATION_SOLVER_NAME,
    DEFAULT_ROOT_METHOD,
    ROOT_SOLVER_NAME,
    SolverConfig,
    evaluate_network,
    run_solver,
    solve_network,
)

__all__ = [
    "Connection",
    "ConnectionModel",
    "ConnectionResult",
    "CONTINUATION_SOLVER_NAME",
    "DarcyPowerLawPipe",
    "DarcyWeisbachPipe",
    "DEFAULT_ROOT_METHOD",
    "DiagnosticItem",
    "FactorPolynomialConnection",
    "LinearInterpolationConnection",
    "ModelSample",
    "Network",
    "Node",
    "NodeResult",
    "ParameterSpec",
    "PolynomialRegressionConnection",
    "PowerLawPipe",
    "ScenarioComparison",
    "SolveResult",
    "SolveTraceStep",
    "SolverConfig",
    "ValidationReport",
    "build_model",
    "build_connection_results_csv",
    "build_model_samples_csv",
    "build_model_samples_payload",
    "build_network_spec",
    "build_diagnostics",
    "build_node_results_csv",
    "build_parameter_template",
    "build_report_csv",
    "build_report_payload",
    "build_scenario_csv",
    "build_text_report",
    "build_trace_csv",
    "clone_network",
    "create_network",
    "darcy_weisbach_friction_factor",
    "darcy_weisbach_head_variation",
    "evaluate_network",
    "export_parameter_schema",
    "fit_power_law_parameters_from_samples",
    "get_model_class",
    "get_model_parameter_schema",
    "get_model_parameter_template",
    "laminar_power_law_parameters",
    "list_model_types",
    "launch_app",
    "local_power_law_head_variation_from_darcy",
    "local_power_law_parameters_from_darcy",
    "load_network",
    "load_network_file",
    "network_from_spec",
    "power_law_flow_rate",
    "power_law_head_variation",
    "ROOT_SOLVER_NAME",
    "run_gui",
    "run_solver",
    "run_scenario_analysis",
    "sample_model",
    "save_network",
    "save_network_file",
    "solve_network",
    "solve_network_file",
    "validate_network_file",
    "validate_parameter_values",
]
